# used similar config from cbkadal
title:       "Operating Systems 2021-2 (OS212)"
description: >- 
  This is a os212 repository!
author:           "Steven Novaryo"
address:          "Pontianak"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://stevennovaryo.github.io/os212-testing/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/stevennovaryo/os212-testing/"
urlghpage:        "https://stevennovaryo.github.io/os212-testing/"
keywords:         "jekyll, testing"
github:           
  - metadata